name: CI Pipeline

on:
  push:
    branches:
      - master
      - "feature/*"
      - "bugfix/*"
      - "hotfix/*"
  pull_request:
    branches:
      - master
      - "develop"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: testdb
          MYSQL_ROOT_PASSWORD: rootkit
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      postgres:
        image: docker.io/postgres:17.2-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: rootkit
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: true
          cache-dependency-path: go.sum

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Install development tools
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run make all (build, test, lint)
        run: make all

      - name: Run MySQL specific tests
        run: go test -tags=mysql -count 1 ./...

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            coverage.out
            coverage.html
          retention-days: 7
