name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - 'feature/*'
      - 'bugfix/*'

jobs:
  test:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: testdb
          MYSQL_ROOT_PASSWORD: rootkit
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      postgres:
        image: docker.io/postgres:17.2-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: rootkit
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Test with the Go CLI use postgres
        run: go test -count 1 ./...

      - name: Test with the Go CLI use mysql
        run: go test -tags=mysql -count 1 ./...